// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngress) DeepCopyInto(out *RoomIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngress.
func (in *RoomIngress) DeepCopy() *RoomIngress {
	if in == nil {
		return nil
	}
	out := new(RoomIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoomIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressList) DeepCopyInto(out *RoomIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoomIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressList.
func (in *RoomIngressList) DeepCopy() *RoomIngressList {
	if in == nil {
		return nil
	}
	out := new(RoomIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoomIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressPlayer) DeepCopyInto(out *RoomIngressPlayer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressPlayer.
func (in *RoomIngressPlayer) DeepCopy() *RoomIngressPlayer {
	if in == nil {
		return nil
	}
	out := new(RoomIngressPlayer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressPlayerStatus) DeepCopyInto(out *RoomIngressPlayerStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	in.Expire.DeepCopyInto(&out.Expire)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressPlayerStatus.
func (in *RoomIngressPlayerStatus) DeepCopy() *RoomIngressPlayerStatus {
	if in == nil {
		return nil
	}
	out := new(RoomIngressPlayerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressRoom) DeepCopyInto(out *RoomIngressRoom) {
	*out = *in
	if in.Players != nil {
		in, out := &in.Players, &out.Players
		*out = make([]RoomIngressPlayer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressRoom.
func (in *RoomIngressRoom) DeepCopy() *RoomIngressRoom {
	if in == nil {
		return nil
	}
	out := new(RoomIngressRoom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressRoomStatus) DeepCopyInto(out *RoomIngressRoomStatus) {
	*out = *in
	if in.Players != nil {
		in, out := &in.Players, &out.Players
		*out = make([]RoomIngressPlayerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressRoomStatus.
func (in *RoomIngressRoomStatus) DeepCopy() *RoomIngressRoomStatus {
	if in == nil {
		return nil
	}
	out := new(RoomIngressRoomStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressSpec) DeepCopyInto(out *RoomIngressSpec) {
	*out = *in
	if in.Rooms != nil {
		in, out := &in.Rooms, &out.Rooms
		*out = make([]RoomIngressRoom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressSpec.
func (in *RoomIngressSpec) DeepCopy() *RoomIngressSpec {
	if in == nil {
		return nil
	}
	out := new(RoomIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoomIngressStatus) DeepCopyInto(out *RoomIngressStatus) {
	*out = *in
	if in.Rooms != nil {
		in, out := &in.Rooms, &out.Rooms
		*out = make([]RoomIngressRoomStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoomIngressStatus.
func (in *RoomIngressStatus) DeepCopy() *RoomIngressStatus {
	if in == nil {
		return nil
	}
	out := new(RoomIngressStatus)
	in.DeepCopyInto(out)
	return out
}
