apiVersion: projectdavinci.com/v1
kind: RoomIngress
metadata:
  name: room1
  namespace: default
spec:
  rules:
    - server: local
      upstream: 127.0.0.1:9200
      players:
        - token: 3
        - token: 4
status:
  proxy:
    addr: 127.0.0.1:4321
