roomproxy:
  debug: false
  workers: 2
  servers:
    - name: local
      host: 0.0.0.0
      port: 4000
      externals: ["47.103.191.190:15000"]
    - name: dev
      host: 0.0.0.0
      port: 5000
      externals: ["47.103.191.190:15001"]
controller:
  reconciler:
    enable: true
  leaderelection:
    enable: true
    id: eed665e4.projectdavinci.com

