roomproxy:
  debug: false
  workers: 2
  servers:
    - name: dev
      host: 0.0.0.0
      port: 4000
      external: "47.103.191.190:15000"
    - name: alpha
      host: 0.0.0.0
      port: 5000
      external: "47.103.191.190:15001"
controller:
  leaderelection:
    enable: true
    id: eed665e4.projectdavinci.com

