apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
# bases:
  # - ../base
resources:
  - crd/projectdavinci.com_roomingresses.yaml
  - rbac/authproxy.yaml
  - rbac/binding.yaml
  - rbac/election.yaml
  - rbac/role.yaml
  - rbac/sa.yaml
  - spiracle.yaml
# patchesStrategicMerge:
  # - patch.yaml
configMapGenerator:
  - name: spiracle-config
    files:
      - config.yaml
