apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spiracle
  namespace: default
spec:
  selector:
    matchLabels:
      app: spiracle
  serviceName: spiracle
  replicas: &replicas 3
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: spiracle
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: spiracle
          image: spiracle:latest
          imagePullPolicy: Never
          command: ["./spiracle"]
          env:
            - name: OLRIC_DISCOVERY_PROVIDER
              value: ""
            - name: OLRIC_DISCOVERY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OLRIC_DISCOVERY_LABEL_NAME
              value: app
            - name: OLRIC_DISCOVERY_LABEL_VALUE
              value: spiracle
            - name: OLRIC_CLIENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 15"]
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          args: ["--secure-listen-address=0.0.0.0:8443", "--upstream=http://127.0.0.1:8080/", "--logtostderr=true", "--v=10"]

---
apiVersion: v1
kind: Service
metadata:
  name: spiracle-metrics-service
  namespace: default
spec:
  selector:
    app: spiracle
  ports:
    - name: https
      port: 8443
      targetPort: https

---
apiVersion: v1
kind: Service
metadata:
  name: spiracle
  namespace: default
spec:
  selector:
    app: spiracle
  type: LoadBalancer
  ports:
    - name: dev
      port: 4000
      targetPort: 4000
      protocol: UDP
    - name: alpha
      port: 5000
      targetPort: 5000
      protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: olric
  namespace: default
spec:
  selector:
    app: spiracle
  type: LoadBalancer
  ports:
    - port: 3320
      targetPort: 3320

---
