
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: spiracle-role
rules:
- apiGroups:
  - projectdavinci.com
  resources:
  - roomingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - projectdavinci.com
  resources:
  - roomingresses/finalizers
  verbs:
  - update
- apiGroups:
  - projectdavinci.com
  resources:
  - roomingresses/status
  verbs:
  - get
  - patch
  - update
